### ISSUE TITLE
[Question]: Any plans on merging with benthos?

### ISSUE THREAD

**Issue by devantler** [united-manufacturing-hub/benthos-umh#13]
Hey, I was wondering if there are any plans/possibilities to merge with Benthos, such that this plugin becomes part of the official inputs and processors?

**Comment by JeremyTheocharis** [comment]
hi, yes we are planning on merging it as soon as it is on a good level. We had first talks with https://github.com/Jeffail, but for now we want to ensure that it works quite stable.

**Comment by devantler** [comment]
This is awesome news! Glad to hear that this is the planned route 🚀
