### ISSUE TITLE
[Feature Request] Support auto discovery and data retrieval from all available OPC PLC nodes.

### ISSUE THREAD

**Issue by devantler** [united-manufacturing-hub/benthos-umh#17]
I have a use case where I need to retrieve all data available from all nodes on an OPC PLC Server. Currently, this requires adding an entry to the `nodeIds` array for each node that I require data from. This does not support my use case, where available nodes might change over time, and the entries should either be deleted or added accordingly.

---

@JeremyTheocharis and co do you have anything planned for a feature like this, and if so, could we collaborate towards a solution? If your lead time for implementing a feature like this is long, I can help out as I need the solution as soon as possible. But if so, I will need some guidance to make sure the solution meets your expectations and goals for how the `benthos-umh` should function.

**Comment by JeremyTheocharis** [comment]
This feature is already in there! Just add the parent node and it will browse (and subscribe) to the rest

**Comment by devantler** [comment]
@JeremyTheocharis Wauw, this is great news! 🙌🏻
How do I do that? Does the parent node have a specific nodeID that I need to use?

**Comment by JeremyTheocharis** [comment]
For example for our WAGO PLC you can use either
`ns=4;s=|var|WAGO 750-8101 PFC100 CS 2ETH.Application.GVL`
or specify the node directly
`ns=4;s=|var|WAGO 750-8101 PFC100 CS 2ETH.Application.GVL.rTemp_DegC`

This is how it looks like in UAExpert
![image](https://github.com/united-manufacturing-hub/benthos-umh/assets/30755722/893d123e-ba20-453a-8f4e-dd84f018a36b)

I think when using i=84 as Node-ID, it should browse the entire thing and susbcribe to everyhting. but that might take some while

**Comment by devantler** [comment]
Thanks! I will look into how this works best for my chosen OPC UA servers :-) The one I am running atm is for testing so it might be enough with `ns=0;i=84` :-)
