### ISSUE TITLE
v0.3.8 fails with with the following error "Configuration file read error: /benthos.yaml: (0,1) unable to infer buffer type from candidates: [none]" 

### ISSUE THREAD

**Issue by devantler** [united-manufacturing-hub/benthos-umh#53]
And v0.3.9 failed in on its publish job. Not sure what causes this issue, but I thought this might be what you tried to fix with v0.3.9 that didnt get published correctly.

**Comment by JeremyTheocharis** [comment]
Yes, that problem is known. benthos-umh is released via a rolling release, so new versions might not work properly. Whatever we use in the UMH is considered to be stable, which is at the moment 0.3.7. At the UMH, we do way more additional tests and automated testing pipelines.

**Comment by devantler** [comment]
Thanks, that makes sense. Where is the UMH? I would like to save a link to it, so I can check there next time in case RenovateBot tells me to upgrade our stacks :-)

**Comment by JeremyTheocharis** [comment]
Hmm, I see that this information is not yet available in a publicly available machine-readable format. You could install the UMH (https://umh.docs.umh.app/docs/getstarted/installation/) and check which Benthos version is deployed, but that would be too much effort for a simple dependency update. Alternatively, you could simply ask in our Discord channel whenever you want to update. I think the latter probably offers the best time/effect ratio.

**Comment by devantler** [comment]
Thanks, I will keep an eye on the discord for now 👀 But have you considered doing nightly/dev builds, and keeping the GH releases stable. This would make it a bit easier to track with bots and such, without inferring with your development?

**Comment by JeremyTheocharis** [comment]
we have introduced beta versions now :)
